name: future_pool
description: Execute multiple async functions in parallel with a pooling mechanism
version: 0.0.2
repository: https://github.com/kkristof200/dart-future-pool

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  synchronized: ^3.1.0+1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
